brexhq/substation

cmd/aws/lambda/substation/main.go, cmd/file/substation/main.go, internal/aws/s3manager/s3manager.go
- Improves S3 ingest performance by making the byte allocation for the scanner dynamic based on the size of the file 
- Updates S3 metadata JSON to match other metadata structs
Just a performance improvement I noticed. 🤷 
Tested in our development AWS account on large files uploaded to S3.
=> refactor: Improve S3 Ingest Performance

build/config/README.md, build/config/aws/appconfig_delete.py, build/config/aws/appconfig_upload.py
- Refactors the AppConfig upload script to reduce unnecessary calls to the service
- Adds AppConfig delete script
- Updated documentation in both scripts and README
We recently observed previously unseen rate limit exception errors when querying AppConfig profiles with dozens of hosted configurations, to fix this the `appconfig_upload.py` script only queries for the most recent hosted configuration (that's the only one that matters). 
We've also done some internal cleanup of legacy data pipelines and needed a script to delete unused application profiles (as of today, Terraform cannot force delete any profiles that have hosted configurations). 
The upload script was tested internally in our CI / CD pipeline, the delete script was used to cleanup a few legacy pipelines.
=> feat: AppConfig Script Updates

internal/json/json.go, process/copy_test.go, process/expand.go, process/expand_test.go
- Adds a "data processing pattern" to the Expand processor, it now supports expansion of arrays of objects
- Improves JSON parsing by automatically unescaping JSON strings
We've recently dealt with a dataset that required these changes. Most notably, this dataset contains escaped JSON strings within its JSON objects, similar to:
```
{"foo":"bar","baz":"{\"qux\":\"quux\"}"}
```
With the improvement to JSON parsing, the Copy processor can be used to copy the key `baz` into itself and automatically unescape the JSON string.
There are new unit tests, plus some integration testing with the dataset described above.
=> feat: Improvements to JSON Parsing

build/config/substation.libsonnet
- Adds a new KV store pattern for performing indicator matching against an [Emerging Threats compromised IPs file](https://rules.emergingthreats.net/blockrules/compromised-ips.txt)
It's a nice example of how to use text files for indicator matching, with support for embedding metadata within the event. This one is specific to ET, but can be reused or abstracted for similar use cases. This is submitted as a chore PR so that we don't bump the release version.
Tested locally, which can be recreated by using a simple data file like this ...
```json
{"addr":"102.219.33.178"}
{"addr":"8.8.8.8"}
```
and config like this ...
```jsonnet
local sub = import '../../build/config/substation.libsonnet';
local processors = [
sub.patterns.processor.kv_store.emerging_threats_compromised_address(key='addr', …
```
=> chore: Add Pattern for Emerging Threats Compromised Addresses

build/config/substation.libsonnet, internal/kv/kv.go, internal/kv/mmdb.go
- Adds an MMDB KV store
[MMDB](https://maxmind.github.io/MaxMind-DB/) is an alternative to the IP database (IPDB) component. Unlike that feature, this one does not interpret data from the database before returning it to the caller, which makes it more modular at the expense of potentially requiring more user configuration -- any file in MMDB format is supported.
Tested locally via integration test. Tests can be recreated using these examples:
```jsonnet
local sub = import '../../build/config/substation.libsonnet';
local kv = sub.interfaces.processor.kv_store(
settings={key: 'addr', set_key: 'mmdb'},
options={type: 'get', 'kv_options': sub.interfaces.kv_store.mmdb(
settings={file: '/path/to/file.mmdb'}
)}
);
kv
```
```go
package main
import (
"context"
"encoding/json"
"fmt"
"os" …
```
=> feat: Add MMDB Key-Value Store

build/config/substation.libsonnet, internal/http/http.go, internal/kv/kv.go, internal/secrets/example_test.go, internal/secrets/secrets.go, internal/secrets/secrets_test.go, internal/sink/http.go, internal/sink/sumologic.go, process/example_test.go, process/http.go, process/process.go
- Adds an HTTP processor that fulfills a variety of GET and POST request use cases
- Adds two HTTP processing patterns for interacting with [GreyNoise](https://www.greynoise.io/)
- Adds functionality to retrieve and interpolate secrets from environment variables or [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/)
- Adds capability to use a KV Store outside of the internal package
- Refactors the HTTP and Sumo Logic sinks
Similar to the DNS processor, the HTTP processor lets users enrich data by making HTTP requests (GET or POST). This one is more complex than DNS for two reasons:
- HTTP requests to external services usually require authentication
- HTTP can host more diverse content than DNS can
We're addressing authentication through a feature referred to as secrets …
=> feat: HTTP Processing & Secrets Retrieval

cmd/aws/lambda/substation/s3.go
- Fixes a bug where URL encoded S3 object keys cannot be read
Closes #95.
Integration tested with both S3 and SNS-S3 notifications.
=> fix: AWS S3 Ingest Object Key Decoding

.devcontainer/devcontainer.json, .gitignore, cmd/development/benchmark/main.go, internal/sink/noop.go, internal/sink/sink.go, internal/sink/stdout.go, internal/transform/transform.go
- Adds a development app for benchmarking
- Adds noop (no-op, no operation) transform and sink for enabling zero data processing
- Updates gitignore for profiling binaries generated by benchmark app
- Refactors stdout sink to return an empty struct
The no-op features are helpful for development and integration testing (e.g., deploy a Substation node that doesn't output data but still processes it), and the benchmark app provides an easy way to do application-level performance tests. Here are some examples:
**256 MB memory, 1 CPU**
```sh
$ ./cmd/development/benchmark/benchmark -config examples/quickstart/config.json -input examples/quickstart/data.json 
100000 events in 7.571924086s (13206.68 events/sec)
1 MB in 7.571924086s (0.16 MB/sec)
```
**1 GB memory, 2 CPU**
```sh
$ …
```
=> feat: Add Benchmark App & No-Op Features

process/kv_store.go
- Adds TTLKey option to the KV Store processor
There are cases where it's more effective to use a KV store TTL that is defined in a data object instead of relying only on an offset (e.g., if the data contains a time value that describes when the data will no longer be valid). The offset applies to the value retrieved from TTLKey, otherwise if TTLKey is omitted then the offset behavior is unchanged.
Integration tested with sample events such as:
```json
{"a":"b","ttl":1718770650}
```
The value from `ttl` determines when the item is ejected from the store. If the value isn't in epoch format, then the Time processor can be used to convert it prior to calling the KVStore processor.
=> feat: Add TTL Key to KV Store Processor

examples/terraform/aws/README.md, examples/terraform/aws/kinesis/autoscale/terraform/_provider.tf, examples/terraform/aws/kinesis/autoscale/terraform/_resources.tf
- Adds a Terraform example of deploying a Kinesis Data Stream (KDS) with autoscaling
This helps clarify that the KDS autoscale feature can be used without deploying Substation.
E2E tested in AWS.
=> docs(examples): Add Kinesis Data Stream Autoscale

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/install-dev-tools.sh, .devcontainer/post-create.sh
- Adds support for Docker in Docker within the dev container
- Enforces arm64 in the dev container
- Removes an unused dev container extension
This makes it possible to build containers from within the dev container and simplifies example Terraform deployments.
Tested locally within the dev container.
=> build(devcontainer): Docker in Docker

examples/Makefile
This is in addition to https://github.com/brexhq/substation/pull/157:
- Add AWS_DEFAULT_REGION for AppConfig uploads during builds
- Truncates SUBSTATION_VERSION to ignore abbreviations (`v1.2.0-3-g2821f58` becomes `v1.2.0`)
E2E tested with the docs in the README.
=> docs(examples): Makefile Updates

build/scripts/aws/appconfig/appconfig_delete.py
- Adds pagination to the AppConfig deletion script
This is required for really big deployments, otherwise configuration profiles are missed when the map is generated.
Tested locally against a production AppConfig application.
=> chore(scripts): Add Pagination to AppConfig Deletion Script

cmd/README.md, cmd/development/kinesis-tap/substation/README.md, cmd/development/kinesis-tap/substation/config.jsonnet, cmd/development/kinesis-tap/substation/main.go, examples/cmd/development/tap_kinesis/substation/main.go, internal/aws/kinesis/kinesis.go
- Adds a development app for tapping an AWS Kinesis Data Stream.
This is useful for testing configurations against live data and has some other uses, too (like previewing data in a Kinesis Data Stream). Note that [apps in `cmd/development/` do not follow SemVer](https://github.com/brexhq/substation/blob/main/VERSIONING.md#versioning), so this PR is a `chore` (prevents release-please from incrementing the version number).
See the app's README for more information.
Run this command to preview data in the stream:
```sh
./cmd/development/kinesis-tap/substation -stream-name my-stream
```
Run this command to use a custom configuration:
```sh
./cmd/development/kinesis-tap/substation -stream-name my-stream -config path/to/my/config.json
```
Run this command to choose the stream's offset (defaults …
=> chore(cmd): Add Kinesis Tap Development Application

cmd/development/kinesis-tap/substation/README.md, cmd/development/kinesis-tap/substation/config.jsonnet, examples/config/transform/send/aws_s3_glacier/config.jsonnet, examples/config/transform/utility/message_bytes/config.jsonnet, examples/config/transform/utility/message_freshness/config.jsonnet
- Updates the README for the `kinesis-tap` cmd
- Jsonnet formatting
N/A
N/A
=> docs: Update Kinesis Tap README

build/config/substation.libsonnet, examples/config/transform/aggregate/sample/config.jsonnet, examples/config/transform/array/group/config.jsonnet, examples/config/transform/meta/crash_program/config.jsonnet, examples/config/transform/meta/exactly_once_consumer/config.jsonnet, examples/config/transform/meta/exactly_once_producer/config.jsonnet, examples/config/transform/meta/exactly_once_system/config.jsonnet, examples/config/transform/meta/execution_time/config.jsonnet, examples/config/transform/meta/retry_with_backoff/config.jsonnet, transform/meta_err.go, transform/meta_err_test.go, transform/meta_for_each.go, transform/meta_for_each_test.go, transform/meta_kv_store_lock.go, transform/meta_metric_duration.go, transform/meta_pipeline.go, transform/meta_switch.go, transform/meta_switch_test.go
- Adds `Transforms` field to all meta transform functions
- Deprecates `Transform` field in all meta transform functions
- Deprecates the MetaPipeline transform function
This simplifies the project's use of transform functions by making it so that every meta transform function accepts a list of transform functions (instead of only a single transform function). In v2.0 the existing `transform` support and the MetaPipeline transform will be removed.
For the existing transforms both `transform` and `transforms` fields have to be supported simultaneously to not introduce a breaking change, like this:
```go
if len(tf.tfs) > 0 {
msgs, err = Apply(ctx, tf.tfs, msg)
} else {
msgs, err = tf.tf.Transform(ctx, msg)
}
```
Any new meta transform functions should only have a `transforms` field.
- Added …
=> feat(transform): Add Multi-Transform Support to Meta Transforms

condition/meta_negate.go
- Fixes the wrapped error in the MetaNegate inspector
Noticed that this was wrong when working on another PR.
N/A.
=> fix(condition): Update Wrapped Error in MetaNegate Inspector

examples/config/condition/number/config.jsonnet, examples/config/condition/number/data.json, examples/config/condition/string/config.jsonnet, examples/config/condition/string/data.json
Adds usage examples under string and number conditions.
This complements the Substation readme with a bit more detailed example.
Compiled the configs and got the expected results.
=> docs(examples): add string and number condition examples

build/config/substation.libsonnet, cmd/aws/lambda/substation/s3.go, examples/cmd/client/file/substation/main.go, examples/config/transform/format/zip/config.jsonnet, examples/config/transform/format/zip/data.csv, examples/config/transform/format/zip/data.jsonl, internal/bufio/bufio.go, transform/format_from_zip.go, transform/format_from_zip_test.go, transform/transform.go
- Adds support for non-text (binary) files to all file reading apps
- Adds `FormatFromZip` transform for unarchiving Zip files
This adds basic support for unarchiving Zip files (mentioned in #219). Most data processing systems don't work on archive files, so this doesn't add a complementary `FormatToZip` transform (that would require much more design work). 
The more important addition in this PR is support for non-text files -- in pre-v1.0 this behavior was configurable using an environment variable, but now it's dynamic based on media (file) type. This could go in two directions in the future:
- Add more transforms like `FormatFromZip` (these can be configurable)
- Add support for dynamic unarchiving (similar to existing decompression) (these _cannot_ be configurable)
I'm inclined to …
=> feat(transform): Add FormatFromZip Transform

go.mod
- Uses `1.N.P` version syntax in `go.mod`
This is [causing issues with CodeQL](https://github.com/brexhq/substation/security/code-scanning/tools/CodeQL/status/configurations/automatic/8babe508ca4410d8c9a5c14531d3aafb9f69887b9605a8ad31f0745ce8911ec4). More info available [here](https://go.dev/doc/toolchain#version).
N/A
=> chore(go.mod): Use 1.N.P Version Syntax

README.md
- Replaces the go.mod badge with an OpenSSF badge in `README.md`
The [OpenSSF score](https://scorecard.dev/viewer/?uri=github.com/brexhq/substation) is more informative than the go.mod badge from an end user point of view.
N/A
=> docs(README): Add OpenSSF Score Badge

condition/format_json_test.go, condition/format_mime_test.go, condition/meta_all_test.go, condition/meta_any_test.go, condition/meta_none_test.go, condition/network_ip_global_unicast_test.go, condition/network_ip_link_local_multicast_test.go, condition/network_ip_link_local_unicast_test.go, condition/network_ip_loopback_test.go, condition/network_ip_multicast_test.go, condition/network_ip_private_test.go, condition/network_ip_unicast_test.go, condition/network_ip_unspecified_test.go, condition/network_ip_valid_test.go, condition/number_bitwise_and_test.go, condition/number_bitwise_not_test.go, condition/number_bitwise_or_test.go, condition/number_bitwise_xor_test.go, condition/number_equal_to_test.go, condition/number_greater_than_test.go, condition/number_length_equal_to_test.go, condition/number_length_greater_than_test.go, condition/number_length_less_than_test.go, condition/number_less_than_test.go, condition/string_contains_test.go, condition/string_ends_with_test.go, condition/string_equal_to_test.go, condition/string_greater_than_test.go, condition/string_match_test.go, condition/string_starts_with_test.go
- Add fuzz tests for `condition`
- This closes #235 
OpenSSF was recently deployed for CI and it calls out fuzzing as a gap. More info available here:
- https://github.com/brexhq/substation/security/code-scanning/31
- https://go.dev/doc/security/fuzz/
=> test(condition): Add Fuzzing

condition/format_json.go, condition/network.go, condition/number.go, go.mod, go.sum
- Fixes incorrect imports for Substation v1 in some `conditions`
These were missed in the upgrade to v2, and should not be referencing v1.
Existing unit tests are still passing, and no new tests are needed.
=> fix(condition): Remove v1 Imports

cmd/substation/demo.go
- Fixes an issue where the CLI tool `substation demo` cannot be run from any location
The existing `substation demo` command relies on the `substation.libsonnet` file in the project's root, and this causes an issue if the demo is not run from a path relative to that file. This pre-compiles the config so that the demo can be run from anywhere.
Reinstall the CLI tool and run `substation demo` from any directory.
=> fix(cmd): Pre-Compile Demo Config

README.md
- Updates the README to reference the CLI tool and unit tests
This is easier than what was there before?
Each recommended command was tested locally.
=> docs(README): Add Test Docs

.github/workflows/code.yml, .github/workflows/conventional_commits.yml, .github/workflows/release_please.yml, .github/workflows/scorecard.yml
- Closes https://github.com/brexhq/substation/security/code-scanning/25
- Closes https://github.com/brexhq/substation/security/code-scanning/26
- Closes https://github.com/brexhq/substation/security/code-scanning/27
Seems a bit obvious, we want to improve the security of the repo. 😆 
N/A (need to confirm after merging to main).
=> ci(workflows): Restrict Permissions

.github/workflows/code.yml, .github/workflows/conventional_commits.yml, .github/workflows/release_please.yml
- Closes https://github.com/brexhq/substation/security/code-scanning/36
- Closes https://github.com/brexhq/substation/security/code-scanning/37
Closing out security notices.
N/A (will confirm after merge to main).
=> ci(workflows): Pin Hashes

CONTRIBUTING.md, README.md
- Adds more information to the contributor guide
- Corrects typo in README
This information may not be obvious to new contributors (and there's probably still more to add).
N/A
=> docs: Update Contributor Guide

README.md
- Makes some README buttons clickable
It's nicer when the buttons are clickable?
N/A
=> docs(README): Make Buttons Clickable

.github/workflows/code.yml
- Closes https://github.com/brexhq/substation/security/code-scanning/39.
N/A
N/A
=> build(workflows): Pin Jsonnet Dependency

.github/workflows/scorecard.yml
Artifact name in the artifact upload action is invalid. Fixing to not include spaces.
=> fix(actions): results upload artifact name
