internal/aws/README.md
internal/aws/cloudwatch/cloudwatch.go
internal/aws/dynamodb/dynamodb.go
internal/aws/kinesis/kinesis.go
internal/aws/lambda/lambda.go
internal/aws/s3manager/s3manager.go
internal/aws/secretsmanager/secretsmanager.go
internal/aws/ssm/ssm.go

- Refactors Kinesis autoscaling thresholds to match the solution [described here](https://aws.amazon.com/blogs/big-data/auto-scaling-amazon-kinesis-data-streams-using-amazon-cloudwatch-and-aws-lambda/)
- Refactors CloudWatch Kinesis alarms to repeat the most recent metric value instead of filling it with a zero value (see [fill repeat here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html))
- Updates documentation
These changes can reduce the cost of Kinesis for all pipelines (reduces unnecessary scale up events by increasing stream capacity if the write volume exceeds the threshold for 5 minutes instead of 1 minute) and increase the reliability of autoscaling for streams that have bursty traffic (by using the most recent metric value).
We've run the …

refactor(aws): Update internal/aws Functions

---

condition/condition.go
condition/condition_test.go
condition/length.go
condition/length_test.go
config/condition.libsonnet
config/process.libsonnet
process/aggregate.go
process/aggregate_test.go
process/concat.go
process/convert.go
process/dynamodb.go
process/flatten.go
process/for_each.go
process/group.go
process/lambda.go
process/math.go
process/process.go
process/process_test.go
process/split.go
process/split_test.go

- Adds Aggregate processor
- Adds Split processor
- Adds Length inspector
- Fixes incorrect JSON parsing logic in some processors
- Updates Condition and Process tests with better support for [table driven tests](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests)
These changes introduce the ability for user-defined aggregation and "de-aggregation" of data. 
Until now the ability to aggregate data was limited to sinks (e.g., Kinesis, Sumo Logic), but this provides flexibility in how users join data together during the transformation process. The primary use case for this is to reduce the number of emitted events, which can be achieved at least two ways:
- [Aggregate data into JSON arrays](https://github.com/brexhq/substation/pull/10/files#diff-777524ea7822511be6057bf60384fcd7d12e …

feat: Data Aggregation

---

config/process.libsonnet
internal/json/json_test.go
process/for_each.go

- Fixes a bug in the ForEach processor when loading a config via Jsonnet
- Fixes incorrect settings in process.libsonnet functions
- Adds missing ForEach and Pipeline libsonnet functions
- Adds new test case for getting multi-line JSON
This fixes an unreported issue that was observed when working with the ForEach processor -- some Jsonnet configurations can create incorrect JSON paths (e.g., `foo.bar.`, the trailing dot is an invalid path). 
This also fixes miscellaneous errors in the process.libsonnet file (missing functions and incorrect settings in functions) and adds a new test case for getting multi-line JSON objects.
Jsonnet changes were tested with local integration tests using the Substation file app.

fix: Process Jsonnet Errors

---

config/process.libsonnet
process/pretty_print.go
process/pretty_print_test.go
process/process.go
process/process_test.go

- Adds PrettyPrint processor
There are rare cases where a [prettyprint](https://en.wikipedia.org/wiki/Prettyprint) / multi-line JSON object may be ingested by Substation pipelines; the most likely cause is from reading a file that contains prettyprint objects. If this happens today, then the JSON object is immediately made invalid because the system reads files line-by-line using a [Scanner](https://pkg.go.dev/bufio#Scanner). For example, reading a file that contains the JSON object below would produce 3 byte inputs (where each line is one byte array): 
```
{
"foo": "bar"
}
```
The PrettyPrint processor addresses this edge case by streaming all bytes in a slice into a [stack](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) and checks for balanced curly brackets (`{` and `}`); if …

feat: PrettyPrint Processor

---

cmd/file/substation/main.go
internal/aws/s3manager/s3manager.go
process/expand.go

- Fixes a regression introduced in https://github.com/brexhq/substation/pull/19 when handling very large S3 files that contain a single line of text
- Refactors the Expand processor to speed up data processing for very large JSON objects that contain 1000s of inner objects in an array
During migration of a data pipeline using https://github.com/brexhq/substation/pull/19 I discovered that it introduced a regression for the edge case of handling very large files downloaded from S3 that contain a single line of text (e.g., files from AWS CloudTrail in very busy AWS accounts).
As a longer term solution, the `s3manager` will do a one-time check on initialization for the amount of memory that can be allocated to a single token in a bufio scanner and uses this pattern:
- by default, the token …

fix: Handling Large S3 Files

---

build/terraform/aws/README.md
build/terraform/aws/iam/main.tf
build/terraform/aws/sns/_variables.tf
build/terraform/aws/sns/main.tf
build/terraform/aws/sns/output.tf
cmd/aws/lambda/substation/main.go
examples/aws/README.md
examples/aws/config/substation_example_sns_source/config.jsonnet
examples/aws/terraform/example_appconfig.tf
examples/aws/terraform/example_kinesis.tf
examples/aws/terraform/example_kms.tf
examples/aws/terraform/example_lambda_source_sns.tf

- Adds forward compatibility for Lambda triggers that rely on SNS topics
- Changes the ingest metadata structures to use camelCase JSON keys
We made an early decision to exclusively tie SNS ingest to S3 objects, but SNS is the delivery service for other Lambda triggers as well (e.g., RDS). This PR corrects that mistake by separating SNS ingest into its own function and adds forward compatible support for other services that "ride on" SNS (like S3). We can use the naming convention `[service]-SNS` to trigger the function moving forward. There may be opportunities to do the same thing with SQS in the future and to add an SNS sink, but those are better handled in a separate PR.
I've added a new SNS Terraform module to support the SNS ingest function and added SNS ingest in the example AWS …

feat!: Add Forward Compatibility for SNS

---

internal/aws/kinesis/kinesis.go

Discovered a bug in the ActiveShards method when handling very large streams -- the Kinesis API does not accept both StreamName and NextToken, it's one or the other and using both causes errors.
This was an unknown bug and wasn't discovered until we started seeing anomalous errors with scaling very large streams.
Patched in our production AWS accounts, errors seem to be resolved but this is a bit difficult to test because the error only appears at huge scale. If related issues appear then we'll do another fix.

fix: Kinesis ActiveShards Bug

---

cmd/app.go
cmd/aws/lambda/substation/main.go
cmd/file/substation/main.go
internal/aws/s3manager/s3manager.go

- Fixes an edge case where [http.DetectContentType](https://pkg.go.dev/net/http#DetectContentType) incorrectly identifies Gzip files as not Gzip
- Adds a new environment variable for users to manage how files are read by [scanners](https://pkg.go.dev/bufio#Scanner)
We discovered an edge case where the HTTP DetectContentType method incorrectly identifies Gzip files created by AWS CloudTrail as _not being_ Gzip files. An example is a small file (~1kb) that was identified as `application/vnd.ms-fontobject`. To fix this, I updated the decode method to support file extension matching and the current MIME type matching. This fix is a backwards compatible, non-breaking change.
Since we're fixing file decoding, I figured that this is a good time to add better options for managing file reading …

feat: Improvements to Reading and Decoding Files

---

internal/transform/batch.go
internal/transform/transfer.go

- Adds microsecond delay to the batch transform input to enforce load balancing
I noticed that some of our pipelines were showing symptoms that incoming data was not being balanced across batch transform goroutines (for example, if 1000 events come in, then 500 may go to the first transform, 400 to the second, and 100 to the third). Most users of the system would probably never notice this, but our use of DynamoDB and Lambda for data enrichment made it more apparent as I looked closer at the problem.
Since this transform is designed to read all data from the input channel into a batch (slice of capsules) before applying processing, the fix is to introduce a microsecond delay for each incoming capsule -- from what I saw during testing, this is the smallest amount of time the application …

refactor: Add Micro Delay to the Batch Transformer

---

build/config/condition.libsonnet
condition/condition.go
condition/for_each.go
condition/for_each_test.go
examples/aws/config/substation_example_dynamodb_sink/config.jsonnet
examples/aws/config/substation_example_processor/config.jsonnet
examples/process/encapsulation/config.jsonnet
examples/quickstart/config.jsonnet
examples/service/config.jsonnet

This adds a new condition: `for_each` which acts like the `for_each` processor, applying another condition inspector to all elements of the array. It allows for the inspectors to be applied and to match if none, any, or all inspectors evaluate to true.
Additional changes to jsonnet files are running `jsonnetfmt` across the repo.
This allows for more granular and accurate conditions across lists that previously could only be expressed with regex over the bytes. 
This has be tested with local test cases and used in an internal configuration to meet a need described above.

feat: add for_each condition

---

CONTRIBUTING.md
cmd/app.go
cmd/app_test.go
cmd/aws/lambda/substation/main.go
cmd/file/substation/main.go
condition/content.go
config/config.go
config/example_test.go
examples/service/main.go
internal/aws/appconfig/appconfig.go
internal/aws/s3manager/s3manager.go
internal/aws/s3manager/s3manager_test.go
internal/bufio/bufio.go
internal/bufio/bufio_test.go
internal/bufio/example_test.go
internal/file/example_test.go
internal/file/file.go
internal/media/example_test.go
internal/media/media.go
internal/media/media_test.go
internal/sink/s3.go

- Updates functions and methods that handle streaming data to use the io package
- internal/aws/appconfig
- internal/aws/s3manager
- internal/file
- internal/sink/s3
- Adds a `SetConfig` method to the Substation app that accepts an io.Reader
- Adds an internal package for detecting content (media) type of files
- Adds an internal package that wraps bufio and Scanner
- Moves the SUBSTATION_CONFIG handler from app.go to config.go
- Changes and moves the SUBSTATION_SCAN_METHOD handler from app.go to internal/bufio (breaking)
- Changes the Substation app to make the package private, except for the creation of a new app (breaking)
- Changes all published apps (cmd/aws/lambda, cmd/file, examples/service) to support changes made in this PR
- cmd/file now dynamically retrieves configs from local …

refactor!: Standardizing Use of io

---

process/replace.go
process/replace_test.go

This loosens input checks for the replace processor to omitting a "New" value effectively deleting target substrings.
During processing of input keys it's sometimes desirable to delete substrings that cause errors for downstream systems or are generally unwanted. This allows the `replace` processor to delete substrings if no new option is provided.
Tested with a internal pipeline and added further test harnessed to get coverage of the change.

feat: process.Replace allow replacing with nothing

---

internal/media/media.go

- Adds a static media signature for application/x-gzip
There is an occasional media identification bug when retrieving compressed CloudTrail files from AWS S3 -- [http.DetectContentType](https://pkg.go.dev/net/http#DetectContentType) incorrectly identifies the media type as `application/vnd.ms-fontobject`. The bug is rare (at Brex we process more than 100k compressed CloudTrail files every day and we see the bug, at most, once every few months) but it needs to be fixed because it results in data loss.
The fix was integration tested with a CloudTrail file known to trigger the false match.

fix: Static gzip Media Signature

---

.devcontainer/Dockerfile
.github/workflows/code.yml
build/container/aws/lambda/autoscaling/Dockerfile
build/container/aws/lambda/substation/Dockerfile
build/container/file/Dockerfile
go.mod

Moves all containers to pinned versions of Go 1.19, and updates the minimum supported version as well.
This change reduces the risk of an ambiguous Go version from being deployed without specifying a container tag. It also moves the project's devlopment environment up to the latest stable release to unlock new Go features/updates such as generics and general performance improvements. The current development version Go1.17 is no longer supported and does not receive security fixes so it needs to be upgraded.
At Brex we have been using Go1.19 in production since Substation v0.4.0 due the container not specifying a tag, there have been no issues with this version.

chore: upgrade and pin to Go1.19

---

build/config/patterns.libsonnet
build/config/process.libsonnet
process/dns.go

- Adds an `ErrorOnFailure` field to the DNS processor
Querying DNS with unknown data is likely to result in resolution failures, so this adds a field to explicitly enable errors for certain calls in the processor. This mimics functionality in the Lambda processor and will make its way into other processors through a refactor in 2023.
This also adds a new pattern for querying [Team Cymru's Malware Hash Registry.](https://www.team-cymru.com/mhr) 
Unit tested via `process/example_test.go` (change the IP address to something that doesn't exist, such as `127.0.0.2`). Tests for the MHR pattern are available internally.

fix: DNS errors

---

build/config/substation.libsonnet
condition/for_each.go
condition/ip.go
condition/length.go
condition/strings.go
internal/aws/dynamodb/dynamodb.go
internal/aws/dynamodb/dynamodb_test.go
internal/errors/errors.go
internal/kv/aws_dynamodb.go
internal/kv/csv_file.go
internal/kv/example_test.go
internal/kv/json_file.go
internal/kv/kv.go
internal/kv/memory.go
internal/kv/text_file.go
process/example_test.go
process/kv_store.go
process/process.go

- Adds support for read-write and read-only [key-value stores](https://en.wikipedia.org/wiki/Key%E2%80%93value_database)
- New interface with factory (`internal/kv`)
- Methods for managing stores (Setup, Close), putting values into stores (Set, SetWithTTL), and retrieving values from stores (Get)
- KV backends in this PR:
- AWS DynamoDB (rw)
- Memory (rw)
- CSV File (ro)
- JSON File (ro)
- Text File (ro)
- Adds a `kv_store` processor for retrieving and putting items into any KV store, all features of the KV store interface are supported
- Adds two new patterns for the `kv_store` processor
- cache-aside pattern: performs a [cache-aside](https://docs.aws.amazon.com/whitepapers/latest/database-caching-strategies-using-redis/caching-patterns.html) by retrieving a value from a configured KV …

feat: Add Key-Value Store Functionality

---

build/config/substation.libsonnet
build/terraform/aws/dynamodb/main.tf
build/terraform/aws/iam/main.tf
internal/kv/aws_dynamodb.go

- Adds Sort (Range) Key support to the AWS DynamoDB KV store
- Fixes a bug in the kv_store.cache_aside pattern that caused unnecessary sets to KV stores
- Updated Terraform configs
This is an addendum to #66 to provide support for DynamoDB tables that follow [single-table design](https://aws.amazon.com/blogs/compute/creating-a-single-table-design-with-amazon-dynamodb/), fix a bug in the KV store cache-aside pattern, and clean up some Terraform modules.
Integration tested with DynamoDB tables that use primary keys (partition key) and composite primary keys (partition key and sort key).

feat: Add Sort Key Support to the AWS DynamoDB KV Store

---

build/config/substation.libsonnet

This handles copy/paste errors and `jsonnet-lint` cases in the `substation.libsonnet` library file.
This change improves Jsonnet code quality by reducing errors such as unused variables, and copy-paste mistakes. We can't enable jsonnet-lint in CI because there are false positive lints that can't be overridden.
Changes here have been used in internal pipelines and ensured it works correctly.

chore: jsonnet-lint updates

---

process/aggregate.go
process/capture.go
process/capture_test.go

- Fixes an options error in the Aggregate processor
- Fixes an options error in the Capture processor
Discovered these bugs while testing some configurations
Tested locally, this doesn't affect any other areas of code.

fix: Aggregate & Capture Processor Options

---

process/capture.go
process/capture_test.go

- Adds named group support to object interpretation in the Capture processor
Okta's audit logs contain unusual pseudo-JSON like this ...
```json
{
"debugContext": {
"debugData": {
"behaviors": "{New Geo-Location=NEGATIVE, New Device=NEGATIVE, New IP=NEGATIVE, New State=NEGATIVE, New Country=NEGATIVE, Velocity=NEGATIVE, New City=NEGATIVE}"
}
}
}
```
... that would be much better if it were like this instead:
```json
{
"debugContext": {
"debugData": {
"behaviors": {
"New Geo-Location": "NEGATIVE",
"New Device": "NEGATIVE",
"New IP": "NEGATIVE",
"New State": "NEGATIVE",
"New Country": "NEGATIVE",
"Velocity": "NEGATIVE",
"New City": "NEGATIVE"
}
}
}
}
```
This PR makes that possible by nesting captured fields under the `set_key` configuration.
Added new unit testing.

feat: Add Object Interpretation to Capture Named Groups

---

process/expand.go
process/expand_test.go

- Adds SetKey support to the Expand processor
Some data sources have complex object structures with either deeply nested arrays of objects or multiple layers of arrays of objects. For example:
```json
{
"a": {
"b": {
"c": [{
"d": "e"
}],
"h": {
"i": 1
}
}
},
"j": {
"k": 1
}
}
```
The processor currently pushes `{ "d": "e" }` to the top of the object like this:
```json
{
"d": "e",
"a": {
"b": {
"h": {
"i": 1
}
}
},
"j": {
"k": 1
}
}
```
This makes it nearly impossible to modify the structure of the object after the processor runs because the content of the array is dynamic. This change adds SetKey support which makes this possible (if the SetKey is "x.y"):
```json
{
"a": {
"b": {
"h": {
"i": 1
}
}
},
"j": {
"k": 1
},
"x": {
"y": {
"d": "e"
}
}
}
```
This has some other benefits, like …

feat: Add SetKey Support to Expand Processor

---

.gitignore
cmd/app.go
cmd/development/substation/main.go

This adds a `-force-sink` flag to the `development` app to mutate the Sink configuration to a user overridden value. This currently only supports the standard output sink but can be extended to override HTTP, S3 or any sink.
When iterating on Substation configs and checking output for pipelines typically destined to a remote output a developer needs to edit the configuration's sink to check results. This change often meant for local testing is an error prone chore which can be automated for this use case via the new `-force-sink stdout` flag for the `development` app.
I've been using this locally for a few months to save some config while testing.
```bash
$ substation -h
...
-force-sink string
force sink output to value (supported: stdout)
...
$ substation -force-sink stdout ...
```

feat(CLI): adds force-sink flag

---

build/config/substation.libsonnet
condition/condition.go
condition/condition_test.go

- Adds a Condition inspector
We have some use cases for creating complex conditions that mimic this logic:
- `( foo OR bar ) AND ( baz OR qux )`
- `( foo AND bar ) OR ( baz AND qux )`
The simplest way to do this without a breaking change is to make a Condition inspector, which is a meta method similar to the ForEach inspector or the Pipeline processor. The Condition inspector is a condition (operator and inspectors) that can be referenced in other conditions to create the joined logic shown above. For example, the config below copies the value from `foo` to `bar` if the logic `( length(foo) > 0 AND foo starts_with "x" ) OR ( length(foo) < 4 AND foo equals "bar" )` is true:
```jsonnet
local processors = [
sub.interfaces.processor.copy(
settings={ key: 'foo', set_key: 'bar', condition: …
```

feat: Add Condition Inspector

---

condition/strings.go
condition/strings_test.go

- Adds a `greater_than` type to condition/strings
- Adds a `less_than` type to condition/strings
Lexicographical string comparison can be useful when retroactively parsing data (e.g., during rehydration) or for validating data. These new types use the same syntax as conditions/length.
Added new unit tests.

feat: Add Lexicographical Types to condition/strings

---

build/scripts/aws/README.md
build/scripts/aws/s3/s3_rehydration.py

- Adds a Python script that allows for rehydrating data from S3 into Substation via SNS
This addresses a use case where teams need to rehydrate (re-ingest) data from an S3 bucket into Substation. No new infrastructure is required to use this (if the team is already using SNS notifications for S3), the script simulates the object notification that S3 sends to Lambda.
Integration tested in a development AWS account using an S3 bucket, SNS topic, and Substation Lambda running the AWS_S3_SNS handler.

build: S3 Rehydration Python Script

---

internal/bufio/bufio.go
internal/media/media.go
internal/media/media_test.go

- Adds[ zstd decompression](https://en.wikipedia.org/wiki/Zstd) to bufio
- Adds [Snappy decompression](https://en.wikipedia.org/wiki/Snappy_(compression)) to bufio
zstd and Snappy compression was added in https://github.com/brexhq/substation/pull/93, but decompression (reading) wasn't. Ideally we want to maintain parity in our support for readers and writers so that users can use compressed files without needing external software.
Added unit tests and tested locally using the file sink.

feat: Add Zstandard & Snappy Readers

---

build/terraform/aws/dynamodb/_variables.tf
build/terraform/aws/dynamodb/main.tf
build/terraform/aws/iam/main.tf
cmd/aws/lambda/substation/dynamodb.go
cmd/aws/lambda/substation/main.go
internal/aws/dynamodb/dynamodb.go

- Adds support for AWS DynamoDB ingest
- Updates `build/terraform/aws/dynamodb` to enable Stream on tables
This adds ingest support for [DynamoDB Streams](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html) and enables change data capture (CDC) use cases. ([More info about CDC here](https://www.oreilly.com/library/view/streaming-change-data/9781492032526/ch01.html).) Some example usage:
- Observability on changes made to tables
- Sending notifications for specific types of changes
- Replicating enrichment data from short-term to long-term storage
DynamoDB is schemaless and records generated by the [DynamoDB Stream source](https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html) aren't structured in a way that makes them easily consumed, so this transforms the …

feat: AWS DynamoDB Ingest (CDC)

---

process/http.go

- Changes the URL interpolation to match any number of times instead of once
Discovered this while working with an enrichment service that has its own search language, there are some scenarios where it's helpful to interpolate the same value multiple times. For example: `url:"hxxps://foo.com/?query=( a:"${data}" AND b:"*${data}" )`. Since this goes from supporting a single interpolation to many interpolations this should be non-breaking.
Also, this doesn't add support for interpolating multiple values, just interpolating the same value multiple times. Multi-value interpolation would have bigger impact but could be possible.
Integration tested locally and in production data pipelines.

feat: Allow Multiple URL Interpolations in the HTTP Processor

---

build/config/substation.libsonnet
process/kv_store.go

- Fixes a bug in the KV Store processor where the `ttl_key` cannot be used by itself
- Updates the default options for the KV store processor
N/A
Integration tested with production data pipelines.

fix: KV Store Processor TTL Key

---

build/config/substation.libsonnet
internal/kv/json_file.go

- Adds support for [JSON Lines](https://jsonlines.org/) in the JSON File KV store
GJSON has native support for JSON Lines and this is the simplest way to support using them as a KV store.
Integration tested using the development app. The test can be recreated with these configs:
> kv.json
```json
{"a":1}
{"b":2}
{"c":3}
{"d":4}
{"e":5}
```
> process.libsonnet
```jsonnet
local sub = import '../../build/config/substation.libsonnet';
local processors = [
{
processor: sub.interfaces.processor.kv_store(
options={
type: 'get',
kv_options: sub.interfaces.kv_store.json_file(
settings={file: 'kv.json', is_lines: true}
)
},
settings={key: 'bar', set_key: 'kv_store'}
)
},
];
{
processors: sub.helpers.flatten_processors(processors),
}
```
> data.json
```json
{"foo":"a"}
{"bar":"b"}
{"baz":"c"} …
```

feat: Add JSON Lines Support to KV Store

---

build/config/substation.libsonnet
internal/file/example_test.go

Fixes a bug in the `substation.libsonnet` library when using the `for_each` inspector due to referencing an invalid path.
This is required to use the correct settings in the `for_each` inspector.
Fix is applied to our internal substation library and used in production.

fix: use valid path to the for_each inspector settings

---

build/terraform/aws/kinesis_data_stream/main.tf
cmd/aws/lambda/README.md
cmd/aws/lambda/autoscale/main.go
internal/aws/cloudwatch/cloudwatch.go
internal/aws/kinesis/kinesis.go

- Adds a setting to `cmd/autoscale` that configures an upper and lower threshold for triggering Kinesis scaling events
- Adds a tag to any scaled Kinesis streams that is used to disrupt runaway scaling events
- Updates the Kinesis scaling strategy to be dynamic (more shards at the low end and less shards at the high end)
- Updates Kinesis datapoints to support scaling up and down across any time range
These changes make the Kinesis autoscale app closer to the [deprecated sample solution](https://github.com/aws-samples/kinesis-auto-scaling) provided by AWS and adds some new features (like dynamic scaling). The threshold setting is partially based on [DynamoDB's auto scaling solution](https://aws.amazon.com/blogs/database/amazon-dynamodb-auto-scaling-performance-and-cost-optimization-at-any- …

feat(autoscale): Dynamic Kinesis Scaling with Thresholds

---

build/terraform/aws/kinesis_data_stream/main.tf

- Updates the Kinesis CloudWatch alarms to match the default settings used by the [autoscale app](https://github.com/brexhq/substation/blob/main/internal/aws/cloudwatch/cloudwatch.go#L21-L35)
This fixes resource churn that can occur between Terraform and the autoscale app. After first deployment, the autoscale app completely manages these references.
N/A

build(terraform): Update Kinesis CloudWatch Alarm Lifecycle

---

internal/aws/kinesis/kinesis.go
internal/aws/kinesis/kinesis_test.go
transform/send_aws_kinesis_data_stream.go

- Reduces the aggregated Kinesis record size from 1 MB to 25 KB
- Replaces `PutRecord` call with `PutRecords`
Kinesis Data Streams charge based on [PUT payload units](https://aws.amazon.com/kinesis/data-streams/pricing/#:~:text=A%20PUT%20Payload%20Unit%20is,million%20PUT%20Payload%20Units%20rate.), which have a minimum size of 25 KB. Historically the project aggregated up to the Kinesis limit of 1 MB because there was no support for the `PutRecords` API, but as of v1.0 there is. There's little (or no) value in sending aggregated records larger than 25 KB and by sending them via `PutRecords` the throughput performance increases by ~33% to ~50% (see screenshot). 
This was tested on a high-volume, production data pipeline.

perf(aws): Reduce Aggregated Kinesis Record Size

---

build/terraform/aws/kinesis_data_stream/main.tf

- Removes the lifecycle locals in the Terraform Kinesis Data Stream module
Terraform won't accept variables in lifecycle.ignore_changes and returns the error `A static list expression is required.`. This has been widely discussed in several issues on the Terraform project, with a [particularly long and unresolved discussion here](https://github.com/hashicorp/terraform/issues/3116).

build(terraform): Remove Lifecycle Locals in KDS Module

---

build/config/substation.libsonnet
transform/enrich_kv_store_set.go

Fixes a bug in the initializer for the `enrich_kv_store_set` transform. Documentation states that this is an optional parameter, but the initializing function will return an error if it's not set.
Error received:
> transform: enrich_kv_store_set: time: invalid duration ""
This resolved a bug where the application was inconsistent with the documentation.
Validated that the config from the documentation can be loaded by the application, previously this errored during load.
```jsonnet
sub.transform.enrich.kv_store.set(
// The value of `domain` is put into the KV store as the value of `ip`.
settings={kv_store: sub.kv_store.memory(settings={}), object: {source_key: 'ip', target_key: 'domain'}}
)
```

fix(transform): Update Default KV Store TTL offset to 0

---

build/config/substation.libsonnet
examples/terraform/aws/README.md
examples/terraform/aws/s3/retry_on_failure/config/node/config.jsonnet
examples/terraform/aws/s3/retry_on_failure/config/retrier/config.jsonnet
examples/terraform/aws/s3/retry_on_failure/terraform/_provider.tf
examples/terraform/aws/s3/retry_on_failure/terraform/_resources.tf
examples/terraform/aws/s3/retry_on_failure/terraform/node_with_retrier.tf
internal/aws/lambda/lambda.go
internal/aws/lambda/lambda_test.go
transform/send_aws_lambda.go
transform/transform.go

- Adds a `send_aws_lambda` transform
- Adds an example of using the new transform to continuously retry a failed S3 trigger
This resolves https://github.com/brexhq/substation/issues/57 with an emphasis on adding as little new code as possible. It's mostly trivial to build a retry pipeline using existing Substation components. You can test the new example by running this and then uploading a file to the created S3 bucket:
```sh
make check
make build-aws
make deploy-aws DEPLOYMENT_DIR=examples/terraform/aws/s3/retry_on_failure AWS_APPCONFIG_ENV=example
```
End-to-end tested using the added example.

feat(transform): Add Send for AWS Lambda

---

build/terraform/aws/dynamodb/main.tf

- Adds the `BatchWriteItem` permission to the DynamoDB Terraform module
This is required to support the write pattern in the send_aws_dynamodb transform.
Discovered this while working on https://github.com/brexhq/substation/pull/160.

build(terraform): Add BatchWriteItem to DynamoDB Module

---

transform/send_aws_dynamodb.go

- Fixes the sendAWSDynamoDB transform payload
The transform sends the message data, but has broken support for sending a JSON value from the message. This removes the broken support and makes it so this has same behavior as every other send transform (sends message data only).
This was caught during an E2E example test.

fix(transform): AWS DynamoDB Send Payload

---

internal/aws/kinesis/kinesis.go
internal/aws/kinesis/kinesis_test.go
transform/send_aws_kinesis_data_stream.go

Substation uses the `internal/aggregate` package to buffer events with consideration to buffer size, record counts, and durations which shadow the checks here with adherence to Kinesis limits in a more user friendly way. 
Inclusion of the size checks here allowed events between 25KiB and 1MiB to be sent as empty events to destinations.
The fix has been tested on the internal pipeline containing events ranging from 10KiB to 1MiB with no issues.

fix(kinesis): remove Kinesis aggregation size and count limits

---

internal/aws/kinesis/kinesis.go
transform/send_aws_kinesis_data_stream.go

- Adds a 1MB limit to the Kinesis KPL aggregator
KPL records still need a limit, otherwise the Kinesis transform may generate a record bigger than the 1 MB service limit.
Integration tested on data that is known to cause this issue.

fix(kinesis): Limit Aggregated Records to 1MB

---

build/scripts/aws/s3/s3_rehydration.py

- Adds concurrency to the S3 rehydration script
- Fixes a bug in S3 object pagination
- Updates UX (SNS topic variable, logging messages)
This makes S3 rehydration go considerably faster and fixes an issue when paging through more than 1,000 objects. Unless the client has connectivity issues with SNS, there should no error checking required on the threads ([the SNS service has its own message retry policy](https://docs.aws.amazon.com/sns/latest/dg/sns-message-delivery-retries.html)). Futures are stored in a list in case we want to make error checking an option later.
Tested with a production deployment (similar to the S3/SNS example in the repo).

chore(scripts): Add Concurrency to S3 Rehydration

---

build/config/substation.libsonnet
transform/meta_err.go
transform/meta_err_test.go

- Adds an option to configure which error messages should be caught using the Meta Err transform
This transform catches all errors, but there are some cases where only specific errors should be caught while others should crash the application. By default this option is the same as the existing solution, and it matches the behavior used by `ErrorMessages` elsewhere in the app (https://github.com/brexhq/substation/blob/main/internal/aws/config.go#L96).
Added unit test that shows it catching errors when configured.

feat(transform): Add Customizable Errors to MetaErr

---

build/config/substation.libsonnet
examples/config/transform/utility/message_freshness/config.jsonnet
transform/transform.go
transform/utility_metric_freshness.go

- Adds a `utility_metric_freshness` transform with an example
This makes it possible to measure message / data freshness ([commonly used to measure data processing systems](https://sre.google/workbook/data-processing/)). Unlike other metric transforms, this emits two metrics with unique attributes to differentiate them in the downstream monitoring platform. A freshness SLO can be calculated by turning these metrics into a percentage (e.g., `SLO = success / (success + failure)` for a particular pipeline). 
It's up to the user to determine when to begin measuring freshness (as determined by the `object.source_key` timestamp value), but two examples are:
- Measure freshness of an individual pipeline component (using the `time_now` transform)
- Measure end-to-end freshness of an entire …

feat(transform): Add Metric Freshness Transform

---

internal/metrics/aws_cloudwatch_embedded_metrics.go

- Fixes dimensions in the AWS CloudWatch Embedded Metrics destination
This fixes a bug that causes multiple attributes to be incorrectly assigned to dimensions in the metric (discovered while testing https://github.com/brexhq/substation/pull/178 in a production pipeline). The fix has these dimensions:
```
"Dimensions":[["FunctionName","FreshnessType"]]
```
The incorrect dimensions are:
```
"Dimensions":[["FunctionName"],["FreshnessType"]]
```
This bug doesn't impact the metric value, but it does affect filters in CloudWatch (and may affect downstream systems).

fix(metrics): AWS CloudWatch Embedded Metrics Dimensions

---

build/config/substation.libsonnet
transform/meta_kv_store_lock.go

- Replaces the `Object.LockKey` setting with `Object.SourceKey` in the meta_kv_store_lock transform
This matches the pattern used by the two existing KV Store transforms. 
Source code and config file linting.

refactor(transform): Use Object SourceKey in KV Store Lock

---

build/config/substation.libsonnet
build/config/substation_test.jsonnet
condition/condition.go
condition/number.go
condition/number_greater_than.go
condition/number_greater_than_test.go

- Adds `number_greater_than` inspector
This is for comparing a number's value, which is currently only possible using the `string_match` function like this:
```jsonnet
sub.cnd.str.match({ object: {source_key: 'FIELD'}, pattern: '^[0-9]{4,}$'}),  // 1,000+
```
This inspector is simpler to understand:
```jsonnet
sub.cnd.num.greater_than({ object: {source_key: 'FIELD'}, value: 999 }),  // 1,000+
```
The target value type is float64, but this works just as well with integers.
Additional functions can be added later (e.g. `equal_to`, `less_than`). This is nested directly under the `number.*` tree to mimic the naming convention of the `string.*` functions. This probably needs to be considered along with #64, which could either be a new set of nested functions (e.g. `string.compare.equal_to`, …

feat(condition): Add Number Greater Than Inspector

---

build/config/substation.libsonnet
build/config/substation_test.jsonnet
condition/condition.go
condition/number.go
condition/number_less_than.go
condition/number_less_than_test.go

Adds `number_less_than` inspector
Ref: https://github.com/brexhq/substation/pull/183
This is for comparing a number's value, which is currently only possible using the string_match function like this:
`sub.cnd.str.match({ object: {source_key: 'FIELD'}, pattern: '^[0-9]{4,}$'}), `
This inspector is simpler to understand:
`sub.cnd.num.less_than({ object: {source_key: 'FIELD'}, value: 999 }),  // < 999`
The target value type is float64, but this works just as well with integers.
Added unit tests

feat(condition): Add Number Less Than Inspector

---

build/config/substation.libsonnet
build/config/substation_test.jsonnet
condition/condition.go
condition/number.go
condition/number_equal_to.go
condition/number_equal_to_test.go

Adds `number_equal_to` inspector
Ref: https://github.com/brexhq/substation/pull/183
This is for comparing a number's value, which is currently only possible using the string_match function like this:
`sub.cnd.str.match({ object: {source_key: 'FIELD'}, pattern: '^[0-9]{4,}$'}), `
This inspector is simpler to understand:
`sub.cnd.num.equal_to({ object: {source_key: 'FIELD'}, value: 999 }),  // 999`
The target value type is float64, but this works just as well with integers.

feat(condition): Add Number Equal To Inspector

---

build/config/substation.libsonnet

Fixed 'type' attribute of drop transform to `utility_drop` instead of `utility_delay`.

build(config): Updated type attribute in drop transform

---

transform/send_aws_kinesis_data_stream.go

- Changes the payload size limit for Kinesis Data Streams from MiB to MB
Discovered an edge case where the system generated a Kinesis Data Stream payload of more than 5 MB when using the PutRecords API. Changing the limit of each record from 1 MiB (1048576 bytes) to 1 MB (1000000 bytes) fixed the problem. According to the AWS docs, Firehose uses 1 MiB as its message size limit.
Tested E2E in the production data pipeline the bug was discovered in.

fix(transform): Change Kinesis Payload Limit to MB

---

internal/file/file.go
transform/send_aws_s3.go

- Fixes an instance where temporary files are not removed in the AWS S3 send transform
This was discovered while upgrading a large AWS S3 pipeline, over time files build up in the `/tmp` directory of the Lambda container and cause the application to crash. This only occurs if the size of all files is more than 500 MB, but the error is obvious:
```
{
"errorMessage": "transform 119330de-398867f3: write /tmp/substation4083518264: no space left on device",
"errorType": "errorString"
}
```
Tested E2E in the production data pipeline mentioned above.

fix(transform): Remove Temporary Files from AWS S3

---

build/config/substation.libsonnet

Adds the configuration ID in the Substation conditional pattern to locate troublesome configurations from logs.
This was missed during the feature work in #181. Brings feature parity when debugging configurations.
Outputted config.json files now have an `ID` field.

build(config): add ID to conditional pattern

---

build/scripts/aws/dynamodb/bulk_delete_items.py

- Adds a Python script to bulk delete items from DynamoDB
This is useful when you need to bulk delete items from DynamoDB. The JSONL file should contain entries that match the table's schema, like:
```json
{"PK": "abc", "SK":"foo"}
{"PK": "def", "SK":"bar"}
{"PK": "ghi", "SK":"baz"}
```
Tested against a production DynamoDB table.

build(scripts): Add Bulk Delete from DynamoDB Script

---

build/config/substation.libsonnet
condition/meta_err.go
condition/meta_err_test.go

- Adds a new inspector to the condition package to catch errors from other inspectors
This came up while testing #215 in a production data pipeline. This is functionally equivalent to the `MetaErr` transform function. You can work around this problem with existing conditions and transforms (`MetaSwitch`, `UtilityDrop`, etc.), but this is a shortcut to getting the same functionality.
Added unit tests for:
- Catching all errors
- Catching specific errors
- No errors

feat(condition): Add MetaErr Inspector

---

condition/number_equal_to.go
condition/number_equal_to_test.go
condition/number_greater_than.go
condition/number_greater_than_test.go
condition/number_less_than.go
condition/number_less_than_test.go
condition/string_equal_to.go
condition/string_equal_to_test.go
condition/string_greater_than.go
condition/string_greater_than_test.go
condition/string_less_than.go
condition/string_less_than_test.go

Updated the following conditions to support comparisons between source_key and target_key.
- number_equal_to
- number_greater_than
- number_less_than
- string_equal_to
- string_greater_than
- string_less_than
`sub.condition.number.less_than(
settings={object: {source_key: 'a', target_key: 'z'}} 
)
`
`sub.condition.string.less_than(
settings={object: {source_key: 'a', target_key: 'z'}} 
)`
This adds flexibility to accept both static values or `target_key` whichever is provided in the config. Static value is ignored if `target_key` is present in the condition. This solves the issue discussed here: https://github.com/brexhq/substation/issues/64. 
Added unit tests in respective files.

feat(condition): Update conditions to support source and target key comparisons

---

internal/bufio/bufio.go

- Fixes the max token size for bufio scanners
Noticed that this was wrong when working on another PR. These are not equivalent: https://go.dev/play/p/rGQz8_p5zR3. This doesn't affect deployments in AWS Lambda.
Try to read a file with very large lines using any file reader app -- it should fail using the main branch but succeed with this change.

fix(internal/bufio): Default Max Token Size

---

build/config/substation.libsonnet
examples/config/transform/enrich/urlscan/config.jsonnet
examples/config/transform/enrich/urlscan/data.jsonl
examples/config/transform/meta/retry_with_backoff/config.jsonnet
internal/config/config.go
transform/meta_err.go
transform/meta_retry.go
transform/transform.go

- Adds `MetaRetry` transform for retrying transform functions.
- Added urlscan as an example of how the transform works with asynchronous REST APIs.
This is a better implementation of what was previously in the `retry_with_backoff` example and can be used to add strict guarantees when enriching data with an external source (such as a REST API or KV store). For example, this can be used to:
- Retry forever until the transform produces an expected result based on a condition
- Retry any number of times until the transform returns without error
- Retry if an error occurs or a condition fails
This transform will eventually return a limit exceeded error, which can be caught with the `MetaErr` transform if needed with the caveat that this can result in data loss for some transforms (only ones …

feat(transform): Add MetaRetry Transform

---

message/message_test.go

- Adds fuzz tests for `message`
OpenSSF was recently deployed for CI and it calls out fuzzing as a gap, so this is a test to check the level of effort required to address that. More info available here:
- https://github.com/brexhq/substation/security/code-scanning/31
- https://go.dev/doc/security/fuzz/
N/A

test(message): Add Fuzzing

---

cmd/aws/lambda/autoscale/main.go

- Fix security finding for incorrect conversion between integer types (https://github.com/brexhq/substation/security/code-scanning/34 and https://github.com/brexhq/substation/security/code-scanning/35). This adds the upper bound check.
Solves potential overflow issue if the Kinesis downscale and upscale datapoints values are outside the upper bound for int32. This occurs in init - failure should occur pre-runtime if the env var(s) are set incorrectly.
N/A

fix(cmd): Out of Bounds int32 Check in AWS Lambda Autoscale

---

cmd/substation/fmt.go

This change adds support for running `substation fmt` against jsonnet and libsonnet files, automatically normalizing the format of substation configurations.
This change was added to continue making substation more approachable and easy to work with by enhancing the CLI that is used to manage and develop configurations. Right now the CLI supports building and testing. The addition of `substation fmt` adds a very small piece of that puzzle which is ensuring that all configuration is formatted the same way - this improves quality of life for teams managing many configs that are written by multiple developers.
The CLI has been locally built and tested on example jsonnet and libsonnet files to verify functionality.
When running `substation fmt`, the output styling mimics that of `go fmt`, for …

feat: add support for formatting jsonnet with substation cli

---

cmd/substation/build.go
cmd/substation/main.go
cmd/substation/test.go

- Adds `substation build` to the CLI tool
This replaces the [build shell script](https://github.com/brexhq/substation/blob/main/build/scripts/config/compile.sh) and follows the conventions of other CLI tool commands (mimicking the `go` tool).
These readme.com docs need to be updated for the v2.2.0 release:
- https://substation.readme.io/docs/builds (this no longer exists)
- https://substation.readme.io/docs/app-substation (update for new commands)
- https://substation.readme.io/docs/try-substation-on-macos-linux (replace reference to `compile.sh`)
`substation build` was integration tested for a variety of use cases:
- Building individual files
- Building directories
- Building nested directories

feat(cmd): Add build Command to CLI Tool

---

cmd/substation/vet.go
config/config.go

- Adds `substation vet` to the CLI tool
This adds the features of the [AWS Lambda `validate` application](https://github.com/brexhq/substation/blob/main/cmd/aws/lambda/validate/main.go) to the CLI tool, and follows the conventions of other CLI tool commands (mimicking the `go` tool). It provides more info on Substation errors than `validate` by printing the line with the error below the error message, like this:
```sh
vet.jsonnet:3 transform 324f1035-10a51b9a: object_target_key: missing required option
{"type":"hash_sha256","settings":{"id":"324f1035-10a51b9a","object":{"source_key":"foo"}}}
```
The additional output can be ported to `validate` using the addition of the stringer on `config.go`.
`substation vet` was integration tested for a variety of use cases:
- Vetting individual files …

feat(cmd): Add vet Command to CLI Tool

---

.github/workflows/code.yml
.github/workflows/scorecard.yml

- Closes https://github.com/brexhq/substation/security/code-scanning/38
- Adds missed hash for Go setup
- Updates version comment for golangci
GitHub's code scanning did not pick up the pinned hash for black, so I've moved this to black's GitHub action.
N/A (tested on PR).

ci(workflows): Pin More Hashes

---

cmd/substation/playground.go
cmd/substation/playground.tmpl
substation.go

This PR introduces a new locally-served playground for Substation, replacing the previous WASM-based implementation. The new playground is implemented as a Go HTTP server that can be started with the command substation playground. Key changes include:
1. A new playground command added to the Substation CLI.
1. An HTTP server that serves an HTML interface for the playground.
1. Endpoints for running Substation configurations and fetching example configurations.
1. A simple, responsive UI for editing configurations, input data, and viewing output.
1. Provides a simple, flexible, and maintainable way for users to try out and learn substation naturally while keeping maintenance difficulties low for the maintainers by keeping it in the CLI rather than a hosted site.
fixes #259
The new …

feat: added support for new substation playground command

---

message/message.go

- Changes the message package's `Flag` starting number.
[This guidance](https://github.com/uber-go/guide/blob/master/style.md#start-enums-at-one) may be outdated because the iota starts at 1 without requiring addition. This small program shows that `IsControl` (`1`) works as expected (does not start at zero):
```go
package main
import (
"fmt"
"github.com/brexhq/substation/v2/message"
)
func main() {
msg := message.New()
fmt.Println("msg flag 0, ", msg.HasFlag(0))
fmt.Println("msg flag 1, ", msg.HasFlag(1))
ctrl := msg.AsControl()
fmt.Println("ctrl flag 0, ", ctrl.HasFlag(0))
fmt.Println("ctrl flag 1, ", ctrl.HasFlag(1))
}
```
```sh
msg flag 0,  false
msg flag 1,  false
ctrl flag 0,  false
ctrl flag 1,  true
```
See program above.

fix(message): Update Flag Iota

---

cmd/substation/main.go
cmd/substation/playground.go
cmd/substation/test.go
cmd/substation/vet.go

This changes the CLIs "test" subcommand (`substation test`) to log runtime transform errors to standard error. This 
When performing test file driven configuration development it's not clear if a specific tests `[config error]` is from misconfigured Jsonnet declarations, invalid Substation options or runtime errors. You can remove the first two options by diagnosing with `substation vet` but then you still don't know what the runtime transform error is if that's the case. 
Verified that multiple tests across files can be run, and are more clear when there was an opaque `[config error]`.
```zsh
$ substation test .
ok	fizz.libsonnet	607µs
?	buzz.libsonnet	[transform error]
error: transform 907268ad-3907ac72: format 2006-01-02T15:04:05.000000Z location UTC: parsing time …
```

feat(cmd): log test errors

---

transform/test_message.go

- Fixes an issue with test messages due to a missing flag
In v2.3.0 the [Message package was refactored to use Flags for controlling transform behavior that was previously not configurable](https://github.com/brexhq/substation/pull/264), but adding flags to the creation of test messages was missed. This doesn't impact production deployments, so it's not a breaking fix.
Any config unit tests that fail in v2.3.0 due to missing values should now pass.

fix(transform): Add SkipMissingValues Flag to Test Transform

---

MIGRATION.md

This fixes [examples](https://github.com/brexhq/substation/blob/main/MIGRATION.md#metafor_each-condition) in the v2 migration guide for `sub.cnd.meta.*` conditions that replace for_each conditions by removing the array parameter. Users following this guide would get Jsonnet that failed to build.
Discovered this while migrating an old configuration and following the guide resulted in a broken config. 
Verified that the Jsonnet could be built and passed with `substation vet`

docs: update v2 migration guide

---

condition/number_equal_to.go
condition/number_equal_to_test.go
condition/string_equal_to.go
condition/string_equal_to_test.go

Adds additional handling of missing source and/or target keys in condition package number equal to and string equal to.
Fix for issue:Condition Package Zero Value Matches Can Be Inaccurate #263. 
Current behaviour of condition package does not contain source key or target key's  object path existence check. This caused unexpected behaviour:
- When only src key is present but the path doesn't exist, condition package inaccurately matches on zero value and empty string. 
- When both source key and target key are present but both paths do not exist, the number equal to and string equal to return true.
This adds checks thus
-  when source key or target key is present in condition package number equal to and string equal to, but either of path does not exist in the object, then condition equal …

fix(condition): handling of missing source and/or target keys

---

cmd/substation/test.go
cmd/substation/vet.go

Closes #275 by supporting relative imports. 
This fixes the relative import problem by switching the directory to each config (jsonnet, libsonnet) file's directory during every test or vet call.
Tested with an internal repo that has 10s to 100s of config files containing relative imports (`substation test -R`, `substation vet -R`).

fix(cmd): CLI Config Relative Imports

---

cmd/substation/playground.go

This trims the quotes from environment variables set via substation playground to mimic the behaviour of export in bash. 
Often times environment variables are copied from cloud providers eg AWS identity center. Copied token would have "" wrapped and those will be trimmed by export locally. 
The os.Setenv will treat the "" as literal,  this difference handling cause authentication failure. 
Build and tested locally.

fix(playground): trim quotes from environment variables

---

message/message.go
transform/object_copy_test.go

This updates the private setValue helper to conditonally use the correct float or integer encoding per JSON Number type. Relying on the gjson Value method can result in imprecise copies which caused incremented numbers on large integers like the test case added.
As shown in the added test cases bug caused consistent but imprecise copies where a writing a value such as `30400402455622563` would actually set the value of `30400402455622564`.
The new regression tests work, and this has fixed the observed imprecision in our internal deployment.

fix(message): use correct encodings for JSON Number values

---

.github/workflows/release_please.yml
.goreleaser.yaml

- Adds support for [GoReleaser](https://goreleaser.com/).
- Uploads macOS and Linux builds (amd64, arm64) for the Substation CLI to new releases.
Using pre-built binaries for the CLI tool can significantly reduce the time it takes to integrate and use the tool compared to building from source. Building from source takes ~70s on my laptop, but downloading and extracting the pre-built binary takes ~5s.
Example releases are [here](https://github.com/jshlbrd/substation/releases/tag/v4.0.0) and can be tested using these Terminal commands:
```sh
$ wget https://github.com/jshlbrd/substation/releases/download/v4.0.0/substation_Darwin_arm64.tar.gz
$ tar -zxvf substation_Darwin_arm64.tar.gz substation
$ substation -h
```

ci: Add GoReleaser Support for macOS and Linux

---

transform/time_to_string_test.go

Improves test reliability by pinning the test timezone to UTC. GitHub test runners natively run in UTC timezone but this impacted local test runs for developer workstations. 
The test finally passes on my machine. This slightly drove me nuts over the past few months

test: pin test timezone to UTC

---

message/message.go
transform/object_to_string.go
transform/object_to_string_test.go

In #288 a user reported not being able to convert or copy JSON objects into strings either with the `sub.tf.obj.to.str`. This allows JSON objects to be converted to strings by slightly obfuscating the string-ified JSON object, and then fixing that as it's written. 
More context is in #288. The larger question is if this behavior should be applied for transforms where a string JSON object is copied to a new key. Our current behavior would convert the copied string value into a JSON object value.
This adds a new unit test and was tested with the users string in the playground with the users test message.

feat(transform): add JSON object support in the obj_to_string transform

---

cmd/substation/playground.go

Added SkipMissingValues flag in Substation Playground for consistency with other sources.
All unit tests passed.

fix(cmd): Add SkipMissingValues flag in Playground

---

cmd/substation/tap.go

This reduces inconsistency between the message payloads in production Kinesis streams and streams read locally with `substation tap` by setting the metadata in the CLI.
Without this change transforms relying on the metadata would be fail or be incorrect.
I tapped production stream and ensured the correct metadata was set.

feat(cmd): set kinesis metadata in tap CLI

---

cmd/aws/lambda/README.md
cmd/aws/lambda/substation/main.go
cmd/aws/lambda/substation/s3.go

- Adds an S3 -> SQS handler to the AWS Lambda application.
- Refactors all S3 handlers to use the same ingest function.
The AWS Lambda app was missing support for S3 notifications sent over SQS. There's some complexity with this architecture because SQS can also encapsulate SNS, but this change covers both uses under the `AWS_S3_SQS` handler.
This was tested in a production AWS account using an SNS encapsulated SQS queue.

feat(cmd): Add S3-SQS Handler
